In [ ]:
### Basics of Tensors

In [ ]:
import torch

In [ ]:
a=torch.empty(size=(2,3,4))
a

tensor([[[-3.9550e+19,  3.0864e-41,  7.0065e-44,  7.0065e-44],
         [ 6.3058e-44,  6.7262e-44,  6.8664e-44,  6.3058e-44],
         [ 6.8664e-44,  6.8664e-44,  1.1771e-43,  6.7262e-44]],

        [[ 7.5670e-44,  8.1275e-44,  7.1466e-44,  7.5670e-44],
         [ 8.1275e-44,  6.7262e-44,  7.1466e-44,  6.4460e-44],
         [ 6.7262e-44,  6.8664e-44,  6.7262e-44,  7.4269e-44]]])

In [ ]:
torch.ones(size=(3,4))*3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [ ]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.linspace(start=1,end=10,steps=20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [ ]:
import numpy as np
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [ ]:
torch.tensor(arr)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.tensor(arr,dtype=torch.float32)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
t=torch.from_numpy(arr)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
t.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
device = "cuba" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
t=torch.tensor([1,2,3,4],dtype=torch.float32, device=device , requires_grad=True)
t

tensor([1., 2., 3., 4.], requires_grad=True)

In [ ]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
torch.diag(torch.arange(5))

tensor([[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 4]])

In [ ]:
t=torch.arange(5)
t.dtype

torch.int64

In [ ]:
t.double().dtype

torch.float64

##### Tensor Operations 

In [ ]:
torch.rand(size=(3,4))

tensor([[0.9956, 0.1575, 0.0125, 0.7602],
        [0.8989, 0.0207, 0.0444, 0.5194],
        [0.5125, 0.2885, 0.8975, 0.6622]])

In [ ]:
x=torch.ones(size=(3,4))
y=torch.ones(size=(3,4))*4



In [ ]:
print(f'X: {x}')
print(f'Y:{y}')

X: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Y:tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [ ]:
z=x+y
z

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [ ]:
x=torch.ones(size=(3,4))
y=torch.ones(size=(4,5))*4

In [ ]:
torch.matmul(x,y)

tensor([[16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.],
        [16., 16., 16., 16., 16.]])

In [ ]:
batch=10
m=30
n=20
k=10

In [ ]:
x=torch.rand(size=(batch,m,n))
y=torch.rand(size=(batch,n,k))
torch.bmm(x,y).shape


torch.Size([10, 30, 10])

In [ ]:
torch.arange(5)+3

tensor([3, 4, 5, 6, 7])

##### Tensor reshape

In [ ]:
t=torch.arange(15)
t

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
t.shape

torch.Size([15])

In [ ]:
t.unsqueeze(axis=0).shape

torch.Size([1, 15])

In [ ]:
t.unsqueeze(axis=1).shape

torch.Size([15, 1])

In [ ]:
t.unsqueeze(axis=1).squeeze(axis=1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
t.view(3,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [ ]:
t1=torch.linspace(1,15,24)
t1.shape

torch.Size([24])

In [ ]:
t1.view(2,3,4)

tensor([[[ 1.0000,  1.6087,  2.2174,  2.8261],
         [ 3.4348,  4.0435,  4.6522,  5.2609],
         [ 5.8696,  6.4783,  7.0870,  7.6957]],

        [[ 8.3043,  8.9130,  9.5217, 10.1304],
         [10.7391, 11.3478, 11.9565, 12.5652],
         [13.1739, 13.7826, 14.3913, 15.0000]]])

In [ ]:
t1.reshape(2,3,4)

tensor([[[ 1.0000,  1.6087,  2.2174,  2.8261],
         [ 3.4348,  4.0435,  4.6522,  5.2609],
         [ 5.8696,  6.4783,  7.0870,  7.6957]],

        [[ 8.3043,  8.9130,  9.5217, 10.1304],
         [10.7391, 11.3478, 11.9565, 12.5652],
         [13.1739, 13.7826, 14.3913, 15.0000]]])